version: "3.8"

services:
  auth0-demo:
    container_name: auth0-demo
    build: .
    restart: always
    ports:
      - 4001:80
    environment:
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_GITHUB_URL=${VITE_GITHUB_URL}
