name: Deploy

on:
  push:
    branches:
      - main

env:
  VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
  VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
  VITE_GITHUB_URL: ${{ secrets.VITE_GITHUB_URL }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          docker compose up -d --build
